services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      python -m pip install gunicorn==20.1.0
      python -m pip install -r requirements.txt
    startCommand: python -m gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: /opt/render/project/src/.venv/bin:$PATH
    disk:
      name: rag-data
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1 